name: TestRun

on:
  push:
    branches:
      - main

    branches-ignore:
      - feature/test

  pull_request:
    types: [opened, synchronize]

  issues:
    types:
      - opened
      - labeled





